logging:
  level:
    root: INFO
    org.example.app: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/application.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: true

---
# Development profile
spring:
  config:
    activate:
      on-profile: "dev"

logging:
  level:
    com.yourcompany.yourapp: TRACE
    org.springframework.security: DEBUG
  file:
    name: logs/application-dev.log

---
# Production profile
spring:
  config:
    activate:
      on-profile: "prod"

logging:
  level:
    root: WARN
    com.yourcompany.yourapp: INFO
  file:
    name: /var/log/yourapp/application.log